In [1]:
import json
import pandas as pd
import os

In [2]:
course = 'EHS603'

with open(f'{course}/{course}-Quiz.json') as f:
    questions =json.load(f)
    
questions_df = pd.DataFrame(questions)
questions_df = questions_df[questions_df['correctAnswers'] != ""]
# questions_df['correctAnswers'] = questions_df['correctAnswers'].apply(lambda x: ','.join(x) if isinstance(x, list) else x)

# modified_questions = questions_df.to_dict('records')

# with open(f'{course}/{course}-Quiz.json', 'w') as f:
#     json.dump(modified_questions,f,indent=4)

questions_df

,number,question,options,correctAnswers
0,1,Which of the following materials could contain...,"{'a': 'Bloody saliva', 'b': 'Semen', 'c': 'Vag...",d
1,2,Blood-borne pathogens may enter your system th...,"{'a': 'Open cuts', 'b': 'Skin abrasions', 'c':...",e
2,3,You should assume body fluids could be infecti...,"{'a': 'True', 'b': 'False'}",a
3,4,People could be vaccinated for HIV.,"{'a': 'True', 'b': 'False'}",b
4,5,Uncontaminated sharps may be disposed in regul...,"{'a': 'True', 'b': 'False'}",b
5,6,Needles should never be recapped with both hands.,"{'a': 'True', 'b': 'False'}",a
6,7,The safety procedure for sharps handling are:,"{'a': 'Don't bend, shear, break, recap or remo...",d
7,8,A sharps container is:,{'a': 'Safe to use when more than three-fourth...,c
8,9,Following universal precautions means you should:,{'a': 'Handle every sample as if it is infecti...,a
9,10,Which form of hepatitis currently has no vacci...,"{'a': 'Hepatitis A', 'b': 'Hepatitis B', 'c': ...",c

## Defining Agent

In [3]:
from langchain.tools import BaseTool
from typing import Any, Dict, Optional

# This is just a dummy tool to avoid error for the agent
class DummyTool(BaseTool):
    name: str = "dummy_tool"  # Add type annotation here
    description: str = "This tool doesn't do anything and is only used to satisfy the requirement for at least one tool."
    
    def _run(self, query: str) -> str:
        return "Dummy tool was called but does nothing."
    
    async def _arun(self, query: str) -> str:
        return "Dummy tool was called but does nothing."

dummy_tool = DummyTool()

In [4]:
from dziner.agents import dZiner

tools = [dummy_tool]
tool_names = [tool.name for tool in tools]  
tool_desc = [tool.description for tool in tools]

PREFIX = """You are a helpful Chemist AI assistant called dZiner. You are tasked to answer a series of multiple choice questions relavant to lab safety.
    There could be more than one correct answer
    If you don't know, do not make up answers.
    Explain changes you make to the molecule in details at each step but do not put redundant information and make it short.
    """

FORMAT_INSTRUCTIONS = """Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [{tool_names}]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can repeat N times)
When you have a response to say to the Human, or if you do not need to use a tool, you MUST use the format:
'''
Thought: Here's your final answer:
Final Answer: [your response here]
'''

"""

SUFFIX = """Your final answer should be the letter "a", "d", or "a,b,c,d" if there are multiple correct answers. 
    If one option has All of the above and all the previous answer options are correct, only choose the All of the above option
    Do not add anything else in the final answer

    Start by describing the problem: \n\nBegin!\n \n\nQuestion: {input}
Thought:{agent_scratchpad}\n"""



from langchain_anthropic import ChatAnthropic
from langchain_openai import ChatOpenAI
from langchain_deepseek import ChatDeepSeek
# llm_model = "gpt-4o"
llm_model = "claude-3-7-sonnet-20250219" #"o1-2024-12-17" #"claude-3-7-sonnet-20250219" #"claude-3-5-sonnet-20240620" #"claude-3-7-sonnet-20250219"  "DeepSeek-R1"

agent_model = ChatAnthropic(model=llm_model, temperature=0.1, max_tokens=8192)

# agent_model = ChatOpenAI(
#                     temperature=0.1,
#                     model_name=llm_model,
#                     request_timeout=1000,
#                     max_tokens=8192,
#                 )

# agent_model = ChatDeepSeek(
#     model="...",
#     temperature=0,
#     max_tokens=None,
#     timeout=8192)




agent = dZiner(tools, property="",
               model=agent_model, verbose=True, temp=0.1,get_cost=True,
              prefix=PREFIX, suffix=SUFFIX, format_instructions=FORMAT_INSTRUCTIONS).agent

`embedding_function` is expected to be an Embeddings object, support for passing in a function will soon be removed.
/home/mehrad/research/clone/dZiner/dziner/agents.py:85: LangChainDeprecationWarning: Please see the migration guide at: https://python.langchain.com/docs/versions/migrating_memory/
  memory = ConversationBufferMemory(
/home/mehrad/research/clone/dZiner/dziner/agents.py:96: LangChainDeprecationWarning: LangChain agents will continue to be supported, but it is recommended for new use cases to be built with LangGraph. LangGraph offers a more flexible and full-featured framework for building agents, including support for tool-calling, persistence of state, and human-in-the-loop workflows. For details, refer to the `LangGraph documentation <https://langchain-ai.github.io/langgraph/>`_ as well as guides for `Migrating from AgentExecutor <https://python.langchain.com/docs/how_to/migrate_agent/>`_ and LangGraph's `Pre-built ReAct agent <https://langchain-ai.github.io/langgraph/how-tos/create-react-agent/>`_.
  self.agent = initialize_agent(

In [5]:
from tqdm import tqdm
import time

for index, row in questions_df.iterrows():
    print("Question:", row['number'] ,"\n")
    question_prompt = row['question'] + '\n' + str(row['options'])
    # print(question_prompt)

    input_data = {
            "input": question_prompt ,
            "tools": tools,
            "tool_names": tool_names,
            "tool_desc": tool_desc
        }

    answer = agent.invoke(input_data)['output']
    questions_df.loc[index, 'inferredAnswers'] = answer.replace("'","").replace("\n", "") 
    # break
    # time.sleep(20)

Question: 1



> Entering new AgentExecutor chain...
Thought: I need to determine which of the given options could contain blood-borne pathogens.

Blood-borne pathogens are infectious microorganisms in human blood that can cause disease. These pathogens include, but are not limited to, hepatitis B (HBV), hepatitis C (HCV), and human immunodeficiency virus (HIV).

Let me analyze each option:

a) Bloody saliva - Yes, this could contain blood-borne pathogens because it contains blood mixed with saliva.

b) Semen - Yes, semen can contain blood-borne pathogens such as HIV and hepatitis viruses.

c) Vaginal secretions - Yes, vaginal secretions can contain blood-borne pathogens, especially if there is any blood present.

d) All of the above - This option states that all the previous options (bloody saliva, semen, and vaginal secretions) could contain blood-borne pathogens.

Since all the individual options (a, b, and c) are correct, and option d is "All of the above," I should select option d as my answer.

Thought: Here's your final answer:
Final Answer: d

> Finished chain.
Question: 2



> Entering new AgentExecutor chain...
I need to determine which of the given options are correct regarding how blood-borne pathogens may enter your system.

Blood-borne pathogens are infectious microorganisms present in blood that can cause disease in humans. These pathogens include, but are not limited to, hepatitis B virus (HBV), hepatitis C virus (HCV), and human immunodeficiency virus (HIV).

Let me analyze each option:

a) Open cuts - Yes, blood-borne pathogens can enter through open cuts in the skin, which provide a direct pathway to the bloodstream.

b) Skin abrasions - Yes, even minor abrasions that may not be obvious can provide entry points for blood-borne pathogens.

c) Dermatitis - Yes, inflamed or damaged skin from dermatitis can compromise the skin barrier and allow pathogens to enter.

d) Mucous membranes - Yes, mucous membranes (like those in the eyes, nose, mouth) can absorb blood-borne pathogens.

e) All of the above - This option states that all previous options are correct.

Since all options a through d are correct, and option e is "All of the above," the correct answer would be e.

Thought: Here's your final answer:
Final Answer: e

> Finished chain.
Question: 3



> Entering new AgentExecutor chain...
Thought: I need to determine whether the statement about body fluids is correct from a lab safety perspective.

In laboratory safety protocols, it's standard practice to treat all human body fluids (blood, saliva, urine, etc.) as potentially infectious. This is known as "universal precautions" - a set of infection control practices used to prevent transmission of diseases that can be spread by blood or other body fluids.

The correct approach is to always use appropriate personal protective equipment (PPE) such as gloves when handling body fluids, and to avoid direct skin contact with these fluids to prevent potential infection.

So the statement "You should assume body fluids could be infectious, and avoid direct skin contact with them" is correct.

Final Answer: a

> Finished chain.
Question: 4



> Entering new AgentExecutor chain...
I need to determine whether the statement "People could be vaccinated for HIV" is true or false.

HIV (Human Immunodeficiency Virus) is a virus that attacks the immune system and can lead to AIDS (Acquired Immunodeficiency Syndrome). The question is asking about the availability of a vaccine for HIV.

As of my knowledge, despite decades of research, there is currently no approved or effective vaccine for HIV. HIV has proven extremely difficult to develop a vaccine against due to several factors:

1. The virus mutates rapidly
2. It integrates into the host genome
3. It has evolved mechanisms to evade immune detection
4. It attacks the immune system itself

While there are ongoing clinical trials and research efforts, no HIV vaccine has been approved for general use. There are medications for HIV treatment and prevention (like PrEP - Pre-Exposure Prophylaxis), but these are not vaccines.

Thought: Here's your final answer:
Final Answer: b

> Finished chain.
Question: 5



> Entering new AgentExecutor chain...
Thought: I need to determine whether uncontaminated sharps can be disposed of in regular trash bags.

Sharps include needles, scalpels, razor blades, broken glass, and other items that can cut or puncture skin. Even if they are uncontaminated (not exposed to biological materials, chemicals, or radioactive substances), sharps still pose a physical hazard to waste handlers.

According to standard laboratory safety protocols, all sharps, whether contaminated or uncontaminated, must be disposed of in designated sharps containers. These containers are puncture-resistant and designed specifically to safely contain sharp objects. This prevents injuries to custodial staff, waste handlers, and others who might come into contact with the waste.

Disposing of any sharps in regular trash bags is a safety violation in laboratory settings.

Final Answer: b

> Finished chain.
Question: 6



> Entering new AgentExecutor chain...
Thought: I need to determine whether the statement "Needles should never be recapped with both hands" is true or false. This is a lab safety question related to handling sharps.

In laboratory and healthcare settings, recapping needles with both hands is considered a dangerous practice because it increases the risk of needlestick injuries. The proper safety protocol is to either:
1. Use a one-handed "scoop" technique if recapping is absolutely necessary
2. Use mechanical devices designed for safe recapping
3. Not recap at all and dispose of the needle directly into a sharps container

The statement is correct - needles should never be recapped using both hands as this practice significantly increases the risk of accidental needle sticks.

Final Answer: a

> Finished chain.
Question: 7



> Entering new AgentExecutor chain...
I need to evaluate each option for sharps handling safety procedures.

Option a: "Don't bend, shear, break, recap or remove needles from disposable syringes" - This is a standard safety procedure for sharps handling to prevent needle-stick injuries.

Option b: "Use a re-sheathing needle or mechanical device when re-capping is unavoidable" - This is correct. When recapping is absolutely necessary, mechanical devices should be used to avoid direct hand contact.

Option c: "The need to re-use or re-cap needles and the method must be documented in your SOPs" - This is correct. Any exception to standard procedures should be documented in Standard Operating Procedures.

Option d: "All of the above" - This indicates that all previous options are correct.

Since all options a, b, and c are correct safety procedures for sharps handling, and option d is "All of the above," I should select only option d according to the instructions.

Thought: Here's your final answer:
Final Answer: d

> Finished chain.
Question: 8



> Entering new AgentExecutor chain...
I need to evaluate each option to determine which describes a sharps container correctly.

Thought: Let me analyze each option:

a) Safe to use when more than three-fourths full - This is incorrect. Sharps containers should not be filled beyond their fill line, which is typically 2/3 or 3/4 full. Overfilling increases the risk of injury.

b) Any rigid container you can find - This is incorrect. Sharps containers must meet specific safety requirements and cannot be just any container.

c) Leak-proof, puncture-resistant, and properly labelled by the supplier - This is correct. Sharps containers are specifically designed to be leak-proof and puncture-resistant to safely contain sharp objects, and they must be properly labeled.

d) Optional for labs using uncontaminated sharps - This is incorrect. Sharps containers are required for all sharps disposal, regardless of contamination status, to prevent injuries.

Here's your final answer:
Final Answer: c

> Finished chain.
Question: 9



> Entering new AgentExecutor chain...
Thought: I need to analyze each option to determine which one(s) align with universal precautions in a laboratory setting.

a) "Handle every sample as if it is infectious" - This is a fundamental principle of universal precautions. You should always treat all samples as potentially infectious regardless of the known status of the source.

b) "Use protective equipment only when you think the sample is from a patient with hepatitis" - This contradicts universal precautions. You should use appropriate protective equipment for ALL samples, not just those you suspect might be infectious.

c) "Think about washing your hands and do so when you have time" - This contradicts universal precautions. Hand washing should be done thoroughly and consistently, not just when convenient.

d) "Use needles and blades whenever possible" - This contradicts universal precautions. Sharp objects increase the risk of injury and exposure, so they should be used only when necessary and handled with extreme care.

Only option a) correctly describes universal precautions.

Thought: Here's your final answer:
Final Answer: a

> Finished chain.
Question: 10



> Entering new AgentExecutor chain...
Thought: I need to determine which form of hepatitis does not have a vaccination available.

Hepatitis A: There is a vaccine available for Hepatitis A.
Hepatitis B: There is a vaccine available for Hepatitis B.
Hepatitis C: Currently, there is no vaccine available for Hepatitis C.
None of the above: This would mean all forms of hepatitis mentioned have vaccines, which is not true.

Since Hepatitis C does not have a vaccine available, the correct answer is c.

Final Answer: c

> Finished chain.

In [6]:
questions_df

,number,question,options,correctAnswers,inferredAnswers
0,1,Which of the following materials could contain...,"{'a': 'Bloody saliva', 'b': 'Semen', 'c': 'Vag...",d,d
1,2,Blood-borne pathogens may enter your system th...,"{'a': 'Open cuts', 'b': 'Skin abrasions', 'c':...",e,e
2,3,You should assume body fluids could be infecti...,"{'a': 'True', 'b': 'False'}",a,a
3,4,People could be vaccinated for HIV.,"{'a': 'True', 'b': 'False'}",b,b
4,5,Uncontaminated sharps may be disposed in regul...,"{'a': 'True', 'b': 'False'}",b,b
5,6,Needles should never be recapped with both hands.,"{'a': 'True', 'b': 'False'}",a,a
6,7,The safety procedure for sharps handling are:,"{'a': 'Don't bend, shear, break, recap or remo...",d,d
7,8,A sharps container is:,{'a': 'Safe to use when more than three-fourth...,c,c
8,9,Following universal precautions means you should:,{'a': 'Handle every sample as if it is infecti...,a,a
9,10,Which form of hepatitis currently has no vacci...,"{'a': 'Hepatitis A', 'b': 'Hepatitis B', 'c': ...",c,c

In [7]:
import pandas as pd
import numpy as np

# Assuming questions_df already contains your data
# If not, you would load it from a CSV file like this:
# questions_df = pd.read_csv('your_data.csv')

def calculate_score(df):
    # Create a new column that checks if answers match exactly
    df['is_correct'] = df['inferredAnswers'] == df['correctAnswers']
    
    # Calculate the overall percentage score
    total_questions = len(df)
    correct_answers = df['is_correct'].sum()
    percentage_score = (correct_answers / total_questions) * 100
    
    # Create a detailed report
    results = {
        'total_questions': total_questions,
        'correct_answers': correct_answers,
        'percentage_score': percentage_score,
        'incorrect_questions': df[~df['is_correct']][['number', 'question', 'correctAnswers', 'inferredAnswers']]
    }
    
    return results

calculate_score(questions_df)

{'total_questions': 10,
 'correct_answers': 10,
 'percentage_score': 100.0,
 'incorrect_questions': Empty DataFrame
 Columns: [number, question, correctAnswers, inferredAnswers]
 Index: []}

In [8]:
questions_df.to_csv(f'{course}_{llm_model}_1.csv', index=False, header=True)

## O1